### ISSUE TITLE
Improved seed data

### ISSUE THREAD

**Issue by nicksellen** [foodsharing-dev/foodsharing-api#3]
Would be great to have a way to insert useful data into database. Slightly complicated by the database being shared with the foodsharing desktop site which has it's own data seeding system (manual sql for now).

Looks like DoctrineFixturesBundle [1] and AliceBundle [2] are the nice thing with `--append` to keep the other data:

```
./bin/console doctrine:fixtures:load --append
```
This guide [3] looks reasonable too.

[1] http://symfony.com/doc/current/bundles/DoctrineFixturesBundle/index.html
[2] https://github.com/hautelook/AliceBundle#basic-usage
[3] https://knpuniversity.com/screencast/symfony-doctrine/dummy-data

**Comment by NerdyProjects** [comment]
AliceBundle --append is broken for now, but I think it is totally fine to use it in purge mode (which may need to reinitialize database when working on the desktop site) and just add all fixtures as needed.

I setup an example/.

Missing step would be to integrate alice and factory-muffin to reuse "default fakes" for the entities. I tried doing it by having a Factory Service that registered all factories and made them available - but using that in alice __construct did not work as expected. For now, I am fine without the factories here.

**Comment by NerdyProjects** [comment]
Rethinking this, I will get rid of Alice and add tooling to use factory-muffin together with DoctrineFixturesBundle. Even the codeception documentation notes that factory-muffin is similar to Alice...
