### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by nicksellen** [foodsharing-dev/foodsharing-api#5]
I added a very basic test that doesn't really work (`POST /api/v1/session` returns `[]` with invalid credentials).

Not sure what to do about database access, either mocking a repostory, or getting test database setup (a standalone one, or use the one inside the foodsharing docker setup?).

Needs some investigation.

- [x] add basic test infrastructure
- [ ] get test coverage to about _most code_
- [ ] investigate adding a test coverage tool (can plug into codecov too like frontend [1])

[1] https://codecov.io/gh/foodsharing-dev/foodsharing-light

**Comment by nicksellen** [comment]
You can run the tests with:

```
./vendor/bin/simple-phpunit
```

Not sure why there isn't a way to do it from `./bin/console` though... I guess we can add it?

**Comment by NerdyProjects** [comment]
I suggest using an actual test database as this is the only way to test repositories / SQL queries and we have had bugs in those in the desktop version, so I would like to have the possibility of creating tests for that as well.

**Comment by NerdyProjects** [comment]
"Add tests" stays valid, but codeception has been integrated. Should we keep this issue open as a reminder to always add more tests? :D

**Comment by nicksellen** [comment]
Great!

Maybe we have subtasks for this:

- [x] add basic test infrastructure
- [ ] get test coverage to about _most code_
